### ISSUE TITLE
Support for DiffUtil

### ISSUE THREAD

**Issue by Kikju** [gilgoldzweig/Gencycler#4]
Hi, is there a plan to add support for DiffUtil or AsyncListDiffer ?

**Comment by gilgoldzweig** [comment]
The library itself does not generate DiffUtils code but it should work out of the box. 
Boilerplate code for your RecyclerView adapter is the only thing that is actually been generated

**Comment by Kikju** [comment]
@gilgoldzweig you're right, I can use DiffUtil with no problem. 
It would be nice, if I could set an anotation, which will generate something like androidx.recyclerview.widget.ListAdapter which using AsyncListDiffer as "elements" holder.

**Comment by gilgoldzweig** [comment]
Can you share how you would like to see the generated code?

**Comment by Kikju** [comment]
I would like to change, what is inside `goldzweigapps.com.gencycler.GencyclerRecyclerAdapter` or maybe create totally different "parent" class for adapters.

What I mean by that. 
Right now, there is `elements: MutableList<T>` which is holding the data and `var updateUi: Boolean = true` which doing notification. Then you have to do a lot of stuff for changing the data. 

If you could check what's inside `androidx.recyclerview.widget.ListAdapter` you can see instead of keeping the elements by this adapter itself, rather they keep them in `AsyncListDiffer` and provide `submitList` method. 
By this approach, using of DiffUtils would be simpler. 

I can describe issue I have right now. 
I have a problem with synchronizing of DiffUtils results, In case I receive to responses from backend, diff utils callback will not finish and another is started which couse really weird behavior and loss of data. I could fix it with some kind of sync, or I will just simply use `AsyncListDiffer` in parent class.

**Comment by Kikju** [comment]
Hello again,
This is, what I mean.

Base `GencyclerRecyclerAdapter` can be replaced by: 
```
import android.content.Context
import android.os.Build
import android.os.Looper
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.annotation.LayoutRes
import androidx.recyclerview.widget.AsyncDifferConfig
import androidx.recyclerview.widget.DiffUtil
import androidx.recyclerview.widget.ListAdapter
import goldzweigapps.com.annotations.annotations.GencyclerModel
import goldzweigapps.com.gencycler.GencyclerHolder

abstract class GencyclerListAdapter<T: GencyclerModel, VH: GencyclerHolder>(
    context: Context,
    config: AsyncDifferConfig<T>
): ListAdapter<T, VH>(config) {

    constructor(context: Context, diffCallback: DiffUtil.ItemCallback<T>): this(context, AsyncDifferConfig.Builder(diffCallback).build())

    private val inflater: LayoutInflater = LayoutInflater.from(context)

    /**
     * Helper function to inflate the view holder layout,
     * Can be used by any adapter extending this class
     *
     */
    protected fun inflate(@LayoutRes layoutResId: Int, parent: ViewGroup): View =
        inflater.inflate(layoutResId, parent, false)


    /**
     * @return true if the adapter is empty
     */
    open fun isEmpty(): Boolean = currentList.isEmpty()

    /**
     * @return true if the adapter is not empty
     */
    open fun isNotEmpty(): Boolean = !isEmpty()

    /**
     * Custom '[]' operator
     *
     * allows us the get an item by position
     *
     * @sample yourAdapter[1]
     * @return will return the element at first position
     */
    open operator fun get(position: Int): T = getItem(position)

    /**
     * Custom '[]' operator
     *
     * allows us the get an item by position
     *
     * @sample yourAdapter[element]
     * @return will return the position of the element or -1
     */
    open operator fun get(element: T): Int = currentList.indexOf(element)

    /**
     * Custom 'in' operator
     *
     * allows us to check if an item exist in the adapter
     *
     * @sample element in yourAdapter
     * @return will return if the item exist in the adapter
     */
    open operator fun contains(element: T): Boolean = element in currentList

    /**
     * Checks if the current thread is Ui thread
     *
     * @return true if the current thread is Ui thread
     */
    private fun isUiThread(): Boolean {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            Looper.getMainLooper().isCurrentThread
        }
        else {
            Thread.currentThread() == Looper.getMainLooper().thread
        }
    }

}
```
Note:
I removed add, remove, replace, minus, swap, clear methods, because they are not needed, if `submitList` will be used for every change.


and then, generated adapter:
```
abstract class GeneratedCustomAdapter constructor(
    context: Context,
    config: AsyncDifferConfig<Title>
): GencyclerListAdapter<Title, TitleViewHolder>(context, config) {
// same stuff
    override fun onBindViewHolder(holder: TitleViewHolder, position: Int) {
        onBindTitleViewHolder(holder, get(position), position)
    }
// same stuff
}
```

**Comment by Kikju** [comment]
Hello,
right now, I found out, in order to access `currentList`, you have to migrate to androidx.

**Comment by Kikju** [comment]
Hello again,
I tried to implement it on top of your `androidx` branch (androidx recyclerview 1.1.0 is required for getting `currentList`.

Could you please check the commits? 
https://github.com/Kikju/Gencycler/commits/diffutil

I'm not sure if it's all what has to be implemented.

Also, I'm getting same error duging build, like from `androidx` branch:
```
e: [kapt] An exception occurred: java.lang.IllegalArgumentException: couldn't make a guess for android.widgetImageView
	at com.squareup.kotlinpoet.ClassName$Companion.bestGuess(TypeName.kt:416)
	at goldzweigapps.com.compiler.generators.ViewHolderGenerator.generateViewProperty(ViewHolderGenerator.kt:104)
	at goldzweigapps.com.compiler.generators.ViewHolderGenerator.generateViewHolder(ViewHolderGenerator.kt:96)
	at goldzweigapps.com.compiler.generators.ViewHolderGenerator.generate(ViewHolderGenerator.kt:41)
	at goldzweigapps.com.compiler.GencyclerProcessor.process(GencyclerProcessor.kt:112)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:147)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:79)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:35)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:224)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:187)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:98)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:97)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:82)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:557)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:82)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:548)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:177)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1558)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
not sure what's wrong here....

**Comment by gilgoldzweig** [comment]
There is an issue with one of the views. There is a mission "."

**Comment by gilgoldzweig** [comment]
Looks interesting, I'll need to verify that all the cases work

**Comment by Kikju** [comment]
I managed to make it run.
I fixed the "." issue and also I found one problem with my code (I forgot to changed generated name and I forgot about generics of AsyncDifferConfig).

But to be honest, I do not use filterable, on click or any other "special" annotation... so cannot confirm that.

I can send push request, but I think, I didn't choose the "right" name for that kind of feature. 
I don't think GeneratedListCusomNameAdapter is self explanatory. (that List bothers me :D )
Any idea here ?
